### ISSUE TITLE
Field declaration error in Safari (Version 13.0.5)

### ISSUE THREAD

**Issue by chrismgraham** [numbas/numbas-extension-programming#8]
In programming.js at the start of the CodeRunner class

```
class CodeRunner {
   queue = Promise.resolve();
```
The public field declaration of `queue` seems to not be supported by Safari before v14.1. 

I had a blind stab, moving it inside the constructor on the next line

```
class CodeRunner {

   constructor() {

      this.queue = Promise.resolve();
       ...
```
which gets past the error, but raises another on line 13 of pyodide_worker.js ("Unhandled Promise Rejection: TypeError: undefined is not a constructor"). 

I stopped there as I don't know what I'm doing and not clear if that error was a result of my previous fix!

**Comment by christianp** [comment]
[Public class fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#Public_fields) are only supported in Safari from 14.1.

The error in `pyodide_worker.js` was due to [`WebAssembly.Global`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Global) only being supported in Safari from 13.1, which Pyodide documents in [their section on supported browsers](https://pyodide.org/en/stable/usage/index.html#supported-browsers).
